// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: PGPData.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct PGPData {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var algo: String = String()

  var keyPacket: Data = SwiftProtobuf.Internal.emptyData

  var dataPacket: Data = SwiftProtobuf.Internal.emptyData

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension PGPData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "PGPData"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "algo"),
    2: .same(proto: "keyPacket"),
    3: .same(proto: "dataPacket"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularStringField(value: &self.algo)
      case 2: try decoder.decodeSingularBytesField(value: &self.keyPacket)
      case 3: try decoder.decodeSingularBytesField(value: &self.dataPacket)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.algo.isEmpty {
      try visitor.visitSingularStringField(value: self.algo, fieldNumber: 1)
    }
    if !self.keyPacket.isEmpty {
      try visitor.visitSingularBytesField(value: self.keyPacket, fieldNumber: 2)
    }
    if !self.dataPacket.isEmpty {
      try visitor.visitSingularBytesField(value: self.dataPacket, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: PGPData, rhs: PGPData) -> Bool {
    if lhs.algo != rhs.algo {return false}
    if lhs.keyPacket != rhs.keyPacket {return false}
    if lhs.dataPacket != rhs.dataPacket {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
